### ISSUE TITLE
Dicas e truques para criar códigos manuteníveis usando Vue.js

### ISSUE THREAD

**Issue by wilcorrea** [vuejsvix/talks#1]
# Dicas e truques para criar códigos manuteníveis usando Vue.js

**Palavras-chave**: `vue`, `mixin`, `extends`, `javascript`, `good practice`

## Nível:

- [ ] [Iniciante](https://github.com/vuejsvix/talks/labels/Nível%20Iniciante)
- [x] [Intermediário](https://github.com/vuejsvix/talks/labels/Nível%20Intermedi%C3%A1rio)
- [ ] [Avançado](https://github.com/vuejsvix/talks/labels/Nível%20Avan%C3%A7ado)

## Palestrante

[William Correa](https://github.com/wilcorrea)

## Descrição da palestra

> Escrever códigos para desenhar telas envolve uma certa lógica para guiar o usuário pelos melhores caminhos. Não é incomum repetirmos muito código ou copiarmos e colarmos trechos e ficamos com arquivos grandes e com uma leitura que não agrada nem nós mesmos no segundo momento em que lemos. Nessa talk veremos uma série de exemplos práticos aplicáveis ao nosso dia-a-dia de como tornar nossa base de código mais manutenível distribuindo os recursos de forma mais eficiente e aplicando práticas como SOLID, KISS, DRY, composições com mixins, herança com extends e design patterns como Strategy, State, Factory entre outros.

## Links Úteis

[Slides](https://slides.com/wilcorrea/dicas-e-truques-para-criar-codigo-manuteniveis-usando-vue-js)

**Comment by mikaelhadler** [comment]
Foi muito irado essa talk mano <3
