### ISSUE TITLE
Utilizando ValidationJs com VueJs

### ISSUE THREAD

**Issue by jprando** [vuejsvix/talks#2]
# Utilizando ValidationJs com VueJs

**Palavras-chave**: `vue`, `validacao`, `validationjs`

## Nível

- [X] [Iniciante](https://github.com/vuejsvix/talks/labels/Nível%20Iniciante)
- [ ] [Intermediário](https://github.com/vuejsvix/talks/labels/Nível%20Intermedi%C3%A1rio)
- [ ] [Avançado](https://github.com/vuejsvix/talks/labels/Nível%20Avan%C3%A7ado)

### Jeudi Prando

- [telegram](https://t.me/jeudi)
- [github](https://github.com/jprando)
- [projetos](https://git.jeudi.dev/jeudi)
- [site](https://jeudi.dev)

## Descrição da Palestra

> Toda aplicação precisa validar dados em algum momento, seja no banco de dados, no servidor de aplicação ou na camada de apresentação. Validação tende a ser uma terefa repetitiva principalmente se voce decidir compartilhar as regras entre o servidor de aplicação e a camada de apresentação. Como utilizar a lib que facilite a sua vida e tenha a maioria das validações mais utilizadas para realizar validações nas informações na camada de apresentação escrita em VueJs da sua aplicação? é o que vamos descobrir!

## Links Úteis

[ValidationJs](https://validatejs.org/)

**[Slides](about:blank) (preparando)**

**[Vídeo](about:blank) (pendente)**

**[GitHub](about:blank) (pendente)**

**Comment by wilcorrea** [comment]
Legal, veja se é possível criar validações dinâmicas com essa lib

**Comment by mikaelhadler** [comment]
Só uma linha (; shuahsauhusa, foi irado demais mestre \m/
